### PR TITLE
[3] [UI] JobDetails Android

### LINKED ISSUE #3: [Android] [UI] As a user, I can see the job details page
## Why

As we're creating a demo to show job detail, the user should be able to read the details of a job, including price, location, time, etc before deciding to accept the jobs or not.

## Acceptance Criteria

On job detail screen:
- Implement the title bar with title `Job Detail` and back icon in black `#171923`
- Implement a sticky bottom bar:
  - Show the description as `Get this job to know more about farmer contact information` in black `#171923`
  - Show the price label in black `#171923` and price value `80-95 Baht` green `#2BC65D`
  - Show the `Accept` button in green background `#2BC65D` and white text color `#FFFFFF`

## Design

image

## Resources

- ic_back

### PR DESCRIPTION
**Pull request by lydiasama**
#3 

## What happened 👀

UI for JobDetails Android
 
## Insight 📝

- Initiate Navigation Component and resources that need to use for this screen.
- Create BaseFragment to use the ViewBinding

### CODE REVIEW

**Comment by luongvo** [comment]
@lydiasama conflicts here 👋

**Review by luongvo — COMMENTED** [review]
rest lgtm

**Comment by lydiasama** [comment]
@luongvo Fixed.

**Review by luongvo — APPROVED** [review]
LGTM

**Comment by luongvo** [comment]
@hoangnguyen92dn we need 1 more review here 👋

**Review by hoangnguyen92dn — APPROVED** [review]

**Pull request merged**
